### ISSUE TITLE
Error 400: personFields mask is required. 

### ISSUE THREAD

**Issue by darren0609** [gsuitedevs/go-samples#15]
## Expected Behavior

First time run, unclear as to the specific behavior I am supposed to see, but I believe the error is not one that I am expected to see. 

## Actual Behavior

2018/10/10 08:47:50 Unable to retrieve people. googleapi: Error 400: personFields mask is required. Please specify one or more validpaths. Valid paths are documented at https://developers.google.com/people/api/rest/v1/people/get., badRequest
exit status 1

## Steps to Reproduce the Problem

1. Followed the details as per outlined on https://developers.google.com/people/quickstart/go 
2. Initially was prompted to log into my Google account and authorize. To which I received a token, that I pasted into the console screen. 
3. Console processed the token, and created token.json file. 
4. Error (as per above) appeared. 

## Specifications

- Go version (`go version`)
  go version go1.11.1 darwin/amd64
- OS (Mac)
Darwin <hostname> 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by erickoledadevrel** [comment]
Thanks for the bug report, fixed!
