### ISSUE TITLE
Golang & Google Spreadsheet API V4 - Unable to read a sheet

### ISSUE THREAD

**Issue by Emixam23** [gsuitedevs/go-samples#27]
I've been following the https://developers.google.com/sheets/api/quickstart/go but I couldn't make it work. In fact, I am getting all the time this error:

    2019/01/20 14:39:00 Unable to retrieve data from sheet: Get https://sheets.googleapis.com/v4/spreadsheets/[..............]?alt=json&prettyPrint=false: oauth2: cannot fetch token: 401 Unauthorized
	Response: {
	    "error": "unauthorized_client",
	    "error_description": "Unauthorized"
	}

I first changed the *spreadsheetId* and the *readRange* of the quickstart:

    // Prints the names and majors of students in a sample spreadsheet:
	// https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/edit
	spreadsheetId := "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms"
	readRange := "Class Data!A2:E"
	resp, err := srv.Spreadsheets.Values.Get(spreadsheetId, readRange).Do()
	if err != nil {
		log.Fatalf("Unable to retrieve data from sheet: %v", err)
	}
	
	if len(resp.Values) == 0 {
		fmt.Println("No data found.")
	} else {
		fmt.Println("Name, Major:")
		for _, row := range resp.Values {
		// Print columns A and E, which correspond to indices 0 and 4.
			fmt.Printf("%s, %s\n", row[0], row[4])
		}
	}

Because, since I have already implemented the Google Drive API V3, I put an id of a spreadsheet I have (and used the credentials.json of the account that created this spreadsheet)

However, I am still getting this error, any idea why?

Thanks for any help

PS: Original link: https://stackoverflow.com/questions/54280274/golang-google-spreadsheet-api-v4-unable-to-read-a-sheet

**Comment by erickoledadevrel** [comment]
The error indicates that the refresh token stored in `token.json` doesn't match the client ID stored in `credentials.json`, likely because you mixed and matched files from different accounts. Please delete `token.json` and run the code again to generate a new token with the correct client ID. It doesn't matter which account created `credentials.json`, only that the account that goes through the OAuth2 flow has access to the spreadsheet.

**Comment by Emixam23** [comment]
Hey ! Thanks for your answer. Ok but where is this token.js ?

**Comment by erickoledadevrel** [comment]
It's created automatically in the same directory you run the code from (I believe).
