### ISSUE TITLE
Review Step 1: download credentials.json file 

### ISSUE THREAD

**Issue by lnicolae** [gsuitedevs/go-samples#28]
## Expected Behavior
credentials.json file

## Actual Behavior
How to download credentials.json ?

## Steps to Reproduce the Problem

Step 1: Download credentials.json, how ? I'm not familiar with Google Console Manager, and on browser link dosen't work!

## Specifications

- Go version (`go version`)
- OS (C#/Windows)

**Comment by sqrrrl** [comment]
Which quickstart are you trying?

**Comment by erickoledadevrel** [comment]
It looks like a recent change to the button code broke the flow for users that hadn't already accepted the terms of service. We've reverted the change, please try again.

**Comment by lnicolae** [comment]
.NET samples, (c# code)
  Thanks,   Lautas Nicolae Software engineer 

    On Tuesday, January 29, 2019, 7:53:48 PM GMT+2, Steve Bazyl <notifications@github.com> wrote:  
 
 
Which quickstart are you trying?
