### ISSUE TITLE
where to write these command in google Docs Api that are in Go step 2 part b

### ISSUE THREAD

**Issue by komalNiamat** [gsuitedevs/go-samples#29]
go get -u google.golang.org/api/docs/v1
go get -u golang.org/x/oauth2/google

## Specifications

- Go version (`go version`)
- OS (Windows)

**Comment by erickoledadevrel** [comment]
These are to be entered into the command line.

**Comment by komalNiamat** [comment]
I know these commands are entered in command line but didn't knew that these commands have to entered in the Go command line because I was unaware with GO programming.
So you all have to must comment if you will provide full information otherwise I have knowledge that these have to entered in the command line because it was mentioned in the google docs Api documentation.

**Comment by komalNiamat** [comment]
I was confused with go get command and cmd giving me error that these are not command but Now i knw that these are Go Programming commands where 'get' command will download the files

**Comment by komalNiamat** [comment]
Kindly give the concise information about issue.
Thanks
