### ISSUE TITLE
adminaccess to read all metadata even with accessRole:freeBusyReader

### ISSUE THREAD

**Issue by jliukai** [gsuitedevs/go-samples#33]
## Expected Behavior
given admin access with Oauth2 scope: "https://www.googleapis.com/auth/calendar"
i should be able to see calendar event attendees even if user sets event visibility:private

## Actual Behavior
i see "events" schema data, but no admin visibility to see attendees.
`{
  "accessRole": "freeBusyReader",
  "etag": "\"p32ke99mduu5e60g\"",
  "items": [
    {
      "end": {
        "dateTime": "2017-08-31T17:30:00-07:00"
      },
      "etag": "\"30081064....\"",
      "htmlLink": "https://www.google.com/calendar/event?eid=MGw3aWVz...",
      "iCalUID": "0l7iesgjgpb3q22....@google.com",
      "id": "0l7iesgjgpb....",
      "kind": "calendar#event",
      "start": {
        "dateTime": "2017-08-31T15:30:00-07:00"
      },
      "status": "confirmed",
      "updated": "2017-08-30T00:33:59.851Z",
      "visibility": "private"
    },`

## Steps to Reproduce the Problem

1. used this code https://developers.google.com/calendar/quickstart/go
1. enabled calendar api.
1.  used oauth2.0 client id json file (from gcp> api & services > credentials > oauth2.0 client id > downloaded file.
1. worked with my gsuite team to use admin scope:  "https://www.googleapis.com/auth/calendar" they videochat and showed me i have access to calendar API full read/write access with this exact scope.
1. i can read all my own calendar data.
1. when i read other users on my domain, who set visibility: public, i can see all data
1. when i read other users on my domain, who set visibility: private, i see limited data. im specifically looking for events.Items[x].Attendees data.

## Specifications
- go version go1.12.1 darwin/amd64
- OS Mac

**Comment by sqrrrl** [comment]
That scope does not do what you're trying to accomplish. It only grants the application full access to the calendar of the authorizing user. It does *not*, however, grant any additional access to *other* user's calendars. There isn't any scope that does that. Instead, you need to acquire access tokens to act on behalf of those other users.

I'm curious what information did you read that implied you'd be able to read other user's private events in detail? Just want to make sure docs aren't misleading here.

**Comment by jliukai** [comment]
you are right, https://developers.google.com/calendar/quickstart/go doesnt mention anything about access to other users.

Problem Solved:
needed to signout and sign back into to my work's gmail. power cycling the laptop didnt work. deleting the token.json didnt work.

setup FYI.
1. used this code https://developers.google.com/calendar/quickstart/go
1. enabled calendar api.
1. worked with my corp's gsuite team, to setup an admin user profile for me to use delegated to the GCP project.
1. used oauth2.0 client id json file (from gcp> api & services > credentials > oauth2.0 client id > downloaded file, 
1. log out and log back into Google Services.
