### ISSUE TITLE
sheet/quickstart.go does not work when use "service account credential" token

### ISSUE THREAD

**Issue by tcler** [gsuitedevs/go-samples#35]
## Expected Behavior
works fine

## Actual Behavior
get fail:
 * Unable to parse client secret file to config: oauth2/google: no credentials found

## Steps to Reproduce the Problem
 $ go run quickstart.go

## Specifications
it works after:
  use google.DefaultClient instead google.ConfigFromJSON
'''
        client, err := google.DefaultClient(oauth2.NoContext,
                "https://www.googleapis.com/auth/devstorage.full_control",
                "https://www.googleapis.com/auth/spreadsheets.readonly")
        if err != nil {
                log.Fatal(err)
        }
'''
and need: export GOOGLE_APPLICATION_CREDENTIALS=/path/to/my-token.json  before go run

- Go version (`go version`)
go version go1.10.8 linux/amd64

- OS (Mac/Linux/Windows)
Linux

**Comment by tcler** [comment]
```
package main

import (
	"fmt"
	"log"

	"golang.org/x/oauth2"
	"golang.org/x/oauth2/google"
	"google.golang.org/api/sheets/v4"
)

//export GOOGLE_APPLICATION_CREDENTIALS=/path/to/my-token.json  #before go run

func main() {
	client, err := google.DefaultClient(oauth2.NoContext,
		"https://www.googleapis.com/auth/devstorage.full_control",
		"https://www.googleapis.com/auth/spreadsheets.readonly")
	if err != nil {
		log.Fatal(err)
	}

	srv, err := sheets.New(client)
	if err != nil {
		log.Fatalf("Unable to retrieve Sheets client: %v", err)
	}

	// Prints the names and majors of students in a sample spreadsheet:
	// https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/edit
	spreadsheetId := "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms"
	readRange := "Class Data!A2:E"
	resp, err := srv.Spreadsheets.Values.Get(spreadsheetId, readRange).Do()
	if err != nil {
		log.Fatalf("Unable to retrieve data from sheet: %v", err)
	}

	if len(resp.Values) == 0 {
		fmt.Println("No data found.")
	} else {
		fmt.Println("Name, Major, Gender:")
		for _, row := range resp.Values {
			// Print columns A and E, which correspond to indices 0 and 4.
			fmt.Printf("%s, %s, %s\n", row[0], row[4], row[1])
		}
	}
}
```

**Comment by sqrrrl** [comment]
The quickstart wasn't written to use service accounts and, as you discovered, it's a slightly different code path to do so. If you're looking for examples of using service accounts w/Go, there are some instructions on how to do that at the Go client lib -- https://github.com/googleapis/google-api-go-client
