### ISSUE TITLE
Missing package cloud.google.com/go/compute/metadata

### ISSUE THREAD

**Issue by arnau-rius** [gsuitedevs/go-samples#6]
When running  go run quickstart.go, it fails and returns: ../../../golang.org/x/oauth2/google/default.go:16:2: cannot find package "cloud.google.com/go/compute/metadata" in any of:
	/usr/local/go/src/cloud.google.com/go/compute/metadata (from $GOROOT)
So then you need to run: go get -u cloud.google.com/go/compute/metadata

It would be great to have this step in the Go Quickstart Guide.

**Comment by grant** [comment]
Thanks for the issue. Which quickstart were you running?

**Comment by arnaurius** [comment]
Hi, you're welcome.

I was running this one:
https://developers.google.com/sheets/api/quickstart/go
The concret sample that failed was: *go run quickstart.go*

Thanks.

**Comment by grant** [comment]
I didn't need `go/compute/metadata` when running this. Is this a problem when running on a PC/laptop or just an issue when running on a server.

**Comment by grant** [comment]
Hi @arnaurius,

I just tried this sample without installing compute/metadata from the command line, perhaps it is required in your environment? Are you running from a server? Google Compute Engine? Maybe we can add a note for if you are in this environment.

These are the instructions I followed:

```
go get -u google.golang.org/api/sheets/v4
go get -u golang.org/x/oauth2/...
```

```
go run quickstart.go
Go to the following link in your browser then type the authorization code:
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=59206675741-mt72vm4635ft7ct5ddhudaoikaa6nn3d.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fspreadsheets.readonly&state=state-token
4/QQCTaCWGiYULWQOdHDpAZs35Xt-1qiwi5H2dtdaACq14m1CKDgNnfaU
Saving credential file to: token.json
Name, Major:
Alexandra, English
Andrew, Math
Anna, English
Becky, Art
Benjamin, English
Carl, Art
Carrie, English
Dorothy, Math
Dylan, Math
Edward, English
Ellen, Physics
Fiona, Art
John, Physics
Jonathan, Math
Joseph, English
Josephine, Math
Karen, English
Kevin, Physics
Lisa, Art
Mary, Physics
Maureen, Physics
Nick, Art
Olivia, Physics
Pamela, Math
Patrick, Art
Robert, English
Sean, Physics
Stacy, Math
Thomas, Art
Will, Math
```

Can you state your:
- `go version`
- Operating system

Thanks, Grant

**Comment by arnaurius** [comment]
Hi,

Go version: go version go1.10.3 darwin/amd64
The OS is: macOS 10.13.2.

I had neither installed nor used oauth2 in the past.
Maybe happened to me the same (https://github.com/golang/oauth2/issues/88).

I do not want to waste your time, it was just a comment to help you. :)

Thanks!

**Comment by rusjoan** [comment]
same shit :)

**Comment by rusjoan** [comment]
of course `glide get cloud.google.com/go/compute/metadata` (or `go get ...`) fixed this

**Comment by grant** [comment]
Do you think we should add `go get -u cloud.google.com/go/compute/metadata` to our samples?

**Comment by grglcs** [comment]
I guess so — it would be nice if "quickstart" means real quick start without a hassle

**Comment by grant** [comment]
Can someone create a PR that adds that the metadata `go get` command to each README?

It seems like this fixes everyone's problems.

**Comment by henry-jackson** [comment]
This is a an awesome resource for gsuite! I ran into the same issue and decided to fix the dependency lists. Check PR #25

**Comment by erickoledadevrel** [comment]
I'm not a go expert, but from what I can tell running the command:

```shell
go get -u golang.org/x/oauth2/...
```

Installs the library and the `compute/metadata` dependency. That's the answer on golang/oauth2#88 and I've been able to confirm this on my own machine. Please verify that you are installing with the trailing `/...`.

**Comment by henry-jackson** [comment]
Hey Eric, just checked my bash_history and you're right. I forgot the trailing ellipses which is why I had to get compute/metadata separately. Sorry for the confusion!

**Comment by erickoledadevrel** [comment]
From what I can tell using

```shell
go get -u golang.org/x/oauth2/google
```

Also fetches the dependencies. Is that format clearer?

**Comment by henry-jackson** [comment]
Yeah that command would definitely feel more intuitive in the context of this repo

**Comment by erickoledadevrel** [comment]
Would you be willing to update your PR to switch the READMEs to use that command? I'll do the same in the Quickstart pages in the docs.

**Comment by erickoledadevrel** [comment]
I've updated the instructions in the documentation to use the new version: https://developers.google.com/sheets/api/quickstart/go#step_2_prepare_the_workspace

**Comment by ef2k** [comment]
I started running into this issue last night. At the moment this is the result I'm getting:
```
go get -u golang.org/x/oauth2/...
go: finding golang.org/x/oauth2 latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/net latest
go: finding cloud.google.com/go/compute/metadata latest
go: finding cloud.google.com/go/compute latest
go build cloud.google.com/go/compute/metadata: no Go files in
```

**Comment by henry-jackson** [comment]
> Would you be willing to update your PR to switch the READMEs to use that command? I'll do the same in the Quickstart pages in the docs.

Just updated the PR to reflect these changes

**Comment by erickoledadevrel** [comment]
@ef2k Thanks for the additional detail. Can you provide more information about your environment? What version of Go, what OS, etc. It looks like the last line of your error is cut off:

`No Go files in`

Is there more after that?

**Comment by ef2k** [comment]
@erickoledadevrel, you're welcome. Yes, unfortunately, the error cuts off at that point.
I'm on `go version go1.11.4 darwin/amd64`. OS: `macos 10.14.2` (mojave)

**Comment by erickoledadevrel** [comment]
I just updated to go 1.11.4 on my Mac (running OSX 10.13.6) and it installed fine. Can you include the `-v` flag in your `go get` command, to see if the verbose output has any additional detail?

**Comment by ef2k** [comment]
Thanks for the help. Here's the tail of the log right before it fails. Note: The message is cutoff in the end.

```
$ go get -v -u golang.org/x/oauth2/google
...
Fetching https://cloud.google.com/go?go-get=1
Parsing meta tags from https://cloud.google.com/go?go-get=1 (status code 200)
go: finding cloud.google.com/go/compute/metadata latest
Fetching https://cloud.google.com/go/compute?go-get=1
Parsing meta tags from https://cloud.google.com/go/compute?go-get=1 (status code 200)
get "cloud.google.com/go/compute": found meta tag get.metaImport{Prefix:"cloud.google.com/go", VCS:"git", RepoRoot:"https://code.googlesource.com/gocloud"} at https://cloud.google.com/go/compute?go-get=1
get "cloud.google.com/go/compute": verifying non-authoritative meta tag
go: finding cloud.google.com/go/compute latest
Fetching https://cloud.google.com?go-get=1
Parsing meta tags from https://cloud.google.com?go-get=1 (status code 200)
cloud.google.com/go/compute/metadata
go build cloud.google.com/go/compute/metadata: no Go files in
```

**Comment by ef2k** [comment]
@erickoledadevrel thanks again for the help. I wiped out `$GOPATH/pkg` and ran the `go get` commands again and it fetched successfully this time. All good now. Thanks for your time.

**Comment by erickoledadevrel** [comment]
Turn it off and turn it on again fixes a surprisingly large number of problems :smiley: Glad you got it working, closing this issue.

**Comment by Macifier** [comment]
> I'm not a go expert, but from what I can tell running the command:
> 
> ```shell
> go get -u golang.org/x/oauth2/...
> ```
> 
> Installs the library and the `compute/metadata` dependency. That's the answer on [golang/oauth2#88](https://github.com/golang/oauth2/issues/88) and I've been able to confirm this on my own machine. Please verify that you are installing with the trailing `/...`.

You just saved my life...

**Comment by jcconnell** [comment]
The trailing `/...` solved the issue for me also.
